name: build-mac

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Brew prefix OpenSSL
      run: brew --prefix openssl@1.1

    - name: Install deps
      run: brew install fontconfig freetype openssl@1.1 libxml2 jpeg libpng libtiff

    - name: Configure CMake
      # NOTE: OpenSSL prefix must be explicitly set
      run:
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=`brew --prefix` -DOPENSSL_ROOT_DIR=`brew --prefix openssl@1.1` 

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  run: ctest -C ${{env.BUILD_TYPE}}
