name: build-mac

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Brew prefix
      run: brew --prefix

    - name: Install deps
      run: brew install fontconfig freetype openssl@1.1 libxml2 jpeg libpng libtiff

    - name: Configure CMake
      # NOTE: OpenSSL prefix must be explicitly set
      run: |
        export OPENSSL_ROOT_DIR=`brew --prefix openssl`
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=/usr/local

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  run: ctest -C ${{env.BUILD_TYPE}}
